import type { Metadata } from "next";
import { ThemeModeScript } from 'flowbite-react';
import Nav from "./nav/Nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "IPL Info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
